In [ ]:
from bs4 import BeautifulSoup 
import pandas as pd 
import requests
from time import sleep

In [87]:
def weather_month(year,month,day_start,day_end):
    url = f"http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key=95552a4081f348ce81543624192409&q=San%20Francisco&format=xml&date={year}-{month}-{day_start}&enddate={year}-{month}-{day_end}&tp=1"
    result = requests.get(url)
    result.content
    soup = BeautifulSoup(result.content, "xml")
    soup
    dates = soup.find_all("date")
    hours = soup.find_all("time")
    tempC = soup.find_all("tempC")
    weatherDesc = soup.find_all("weatherDesc")
    precipMM = soup.find_all("precipMM")
    cont = 0
    hour[0].get_text()
    year_list = list()
    month_list = list()
    day_list = list()
    hour_list = list()
    tempC_list = list()
    weatherDesc_list = list()
    precipMM_list = list()
    for i in range(1, len(dates)+1):
        for j in range(cont, cont+24):
            year_list.append(year)
            month_list.append(month)
            day_list.append(i)
            hour_list.append(j%24)
            tempC_list.append(tempC[j].get_text())
            weatherDesc_list.append(weatherDesc[j].get_text())
            precipMM_list.append(precipMM[j].get_text())
            cont += cont
    data_month = {'Year':year_list,'Month':month_list,'Date':day_list,'Hour':hour_list,'tempC':tempC_list,'weatherDesc':weatherDesc_list,'precipMM':precipMM_list}
    data_month_df = pd.DataFrame(data=data_month)
    return(data_month_df)

In [95]:
weather_month_201707 = weather_month(2017,7,1,31)
sleep(5)
weather_month_201708 = weather_month(2017,8,1,31)
sleep(5)
weather_month_201709 = weather_month(2017,9,1,30)
sleep(5)
weather_month_201710 = weather_month(2017,10,1,31)
sleep(5)
weather_month_201711 = weather_month(2017,11,1,30)
sleep(5)
weather_month_201712 = weather_month(2017,12,1,31)
sleep(5)
weather_month_201801 = weather_month(2018,1,1,31)
sleep(5)
weather_month_201802 = weather_month(2018,2,1,28)
sleep(5)
weather_month_201803 = weather_month(2018,3,1,31)
sleep(5)
weather_month_201804 = weather_month(2018,4,1,30)
sleep(5)
weather_month_201805 = weather_month(2018,5,1,31)
sleep(5)
weather_month_201806 = weather_month(2018,6,1,30)
sleep(5)
weather_month_201807 = weather_month(2018,7,1,31)
sleep(5)
weather_month_201808 = weather_month(2018,8,1,31)
sleep(5)
weather_month_201809 = weather_month(2018,9,1,30)
sleep(5)
weather_month_201810 = weather_month(2018,10,1,31)
sleep(5)
weather_month_201811 = weather_month(2018,11,1,30)
sleep(5)
weather_month_201812 = weather_month(2018,12,1,31)
sleep(5)
weather_month_201901 = weather_month(2019,1,1,31)
sleep(5)
weather_month_201902 = weather_month(2019,2,1,28)
sleep(5)
weather_month_201903 = weather_month(2019,3,1,31)
sleep(5)
weather_month_201904 = weather_month(2019,4,1,30)
sleep(5)

In [118]:
weather_complete = pd.concat([weather_month_201707,
weather_month_201708,
weather_month_201709,
weather_month_201710,
weather_month_201711,
weather_month_201712,
weather_month_201801,
weather_month_201802,
weather_month_201803,
weather_month_201804,
weather_month_201805,
weather_month_201806,
weather_month_201807,
weather_month_201808,
weather_month_201809,
weather_month_201810,
weather_month_201811,
weather_month_201812,
weather_month_201901,
weather_month_201902,
weather_month_201903,
weather_month_201904], sort=False).reset_index()
weather_complete.drop("index",axis=1,inplace=True)
weather_complete["Month"].value_counts()

7     1488
12    1488
3     1488
10    1488
1     1488
8     1488
4     1440
11    1440
9     1440
2     1344
5      744
6      720
Name: Month, dtype: int64

In [115]:
weather_complete.head(96)

    Year  Month  Date  Hour tempC    weatherDesc precipMM
0   2017      6     1     0    13  Partly cloudy      0.0
1   2017      6     1     1    13  Partly cloudy      0.0
2   2017      6     1     2    13  Partly cloudy      0.0
3   2017      6     1     3    13  Partly cloudy      0.0
4   2017      6     1     4    13  Partly cloudy      0.0
..   ...    ...   ...   ...   ...            ...      ...
91  2017      7     1    19    15          Sunny      0.0
92  2017      7     1    20    14  Partly cloudy      0.0
93  2017      7     1    21    13  Partly cloudy      0.0
94  2017      7     1    22    13  Partly cloudy      0.0
95  2017      7     1    23    12  Partly cloudy      0.0

[96 rows x 7 columns]

In [119]:
weather_complete.to_csv(r'C:\Users\Victor Leo\Desktop\WeCloud - Python for Data Science\Project 2\Weather_complete.csv')